name: CI

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 'Install development dependencies'
        run: npm ci

      - name: 'Build artifacts'
        run: npm run build

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: public/mike-cousins.pdf

      - name: 'Test artifacts'
        run: npm run test
